sonar.projectKey=evflow-full-app
sonar.projectName=EVFlow

sonar.sources=backend-ev-flow/api,backend-ev-flow/scripts,backend-ev-flow/alembic,frontend-evflow-app/apps,frontend-evflow-app/packages
sonar.tests=backend-ev-flow/tests

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.expo/**,**/*.min.js

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
