"""Payback arithmetic for a proposed site (Epic 5).

This is a calculator, not a forecast. The planner supplies what only they can
know, which is what the equipment costs them and how much demand they are
willing to assume; this module does the arithmetic and refuses when the
arithmetic has no answer. Nothing here predicts demand, because nothing in the
database supports predicting it: production holds eight real charging sessions
from a single user, and the other 1.93 million are generated by
scripts/sql/charging_simulation.sql.

Two refusals carry most of the value.

A site whose revenue does not cover its running costs never pays back. The
obvious expression, capex / (revenue - opex), returns a negative number there,
and a negative payback renders as "-3.2 years", which reads like a fast return
rather than a business losing money every month. So the margin is checked and
the answer is None, with the loss still reported at the horizon so refusing to
give a payback does not mean refusing to say how bad it is.

A site cannot serve more sessions than its connectors physically allow. Demand
above that ceiling is not an optimistic assumption, it is an impossible one, and
quietly clamping it to the ceiling would hide the planner's error while still
producing a confident number.
"""
from __future__ import annotations

import math
from dataclasses import asdict, dataclass

#: Averaged over a year rather than a round 30, so twelve months is a year.
#: Using 30 loses 5.25 days annually, which is 1.4% understated on every
#: revenue figure and quietly optimistic on every payback period.
DAYS_PER_MONTH = 365.25 / 12

HOURS_PER_DAY = 24.0


@dataclass(frozen=True)
class SiteEconomicsInput:
    """Everything the projection rests on, with no hidden defaults.

    Each field is either equipment the planner is buying or an assumption the
    planner is making. The tariff defaults to the one the charging flow actually
    bills at, so a projection and a real session agree on the price of a kWh.
    """
    connectors: int
    power_kw: float
    sessions_per_day: float
    energy_per_session_kwh: float
    capex_per_connector_idr: int
    opex_monthly_idr: int
    tariff_idr_per_kwh: int
    admin_fee_idr: int
    #: What the operator pays for the same kWh it resells. The tariff above is
    #: the driver's price; a charging business keeps only the spread between the
    #: two. Zero means "electricity is already inside my opex figure", which is
    #: a legitimate way to model it but a dangerous thing to assume by accident,
    #: so the projection reports the resulting cost line either way.
    energy_cost_idr_per_kwh: int = 0
    horizon_years: int = 10


def capacity_sessions_per_day(connectors: int, power_kw: float,
                              energy_per_session_kwh: float) -> float:
    """How many sessions the hardware can physically serve in a day.

    Charge time is energy over power, and every connector is available for
    twenty four hours. This is a ceiling, not an expectation: it assumes no idle
    time, no queueing and no overnight lull, so real sites sit far beneath it.
    """
    hours_per_session = energy_per_session_kwh / power_kw
    return connectors * HOURS_PER_DAY / hours_per_session


def _validate(i: SiteEconomicsInput) -> None:
    # Finite first. NaN fails every comparison it takes part in, so a later
    # `power_kw > 0` check would pass it through while reporting the wrong
    # reason, and the division would then produce NaN all the way to the client.
    for name in ("power_kw", "sessions_per_day", "energy_per_session_kwh"):
        value = getattr(i, name)
        if not math.isfinite(value):
            raise ValueError(f"{name} must be finite, got {value}")

    if i.connectors < 1:
        raise ValueError(f"a site needs at least one connector, got {i.connectors}")
    if i.capex_per_connector_idr < 0:
        raise ValueError(f"capex per connector cannot be negative, got {i.capex_per_connector_idr}")
    if i.opex_monthly_idr < 0:
        raise ValueError(f"monthly opex cannot be negative, got {i.opex_monthly_idr}")
    if i.tariff_idr_per_kwh <= 0:
        raise ValueError(f"tariff must be greater than zero, got {i.tariff_idr_per_kwh}")
    if i.admin_fee_idr < 0:
        raise ValueError(f"admin fee cannot be negative, got {i.admin_fee_idr}")
    if i.power_kw <= 0:
        raise ValueError(f"power must be greater than zero, got {i.power_kw}")
    if i.energy_per_session_kwh <= 0:
        raise ValueError(f"energy per session must be greater than zero, got {i.energy_per_session_kwh}")
    if i.energy_cost_idr_per_kwh < 0:
        raise ValueError(f"energy cost per kWh cannot be negative, got {i.energy_cost_idr_per_kwh}")
    if i.sessions_per_day < 0:
        raise ValueError(f"sessions per day cannot be negative, got {i.sessions_per_day}")
    if i.horizon_years < 1:
        raise ValueError(f"horizon must be at least one year, got {i.horizon_years}")


def project(i: SiteEconomicsInput) -> dict:
    """Run the projection, or refuse if the inputs cannot support one."""
    _validate(i)

    capacity = capacity_sessions_per_day(i.connectors, i.power_kw, i.energy_per_session_kwh)
    # Tolerance so that exactly-full utilisation is allowed rather than lost to
    # floating point on the division above.
    if i.sessions_per_day > capacity * (1 + 1e-9):
        raise ValueError(
            f"assumed {i.sessions_per_day:g} sessions per day exceeds the capacity of "
            f"{capacity:.1f} that {i.connectors} connector(s) at {i.power_kw:g} kW can serve "
            f"for {i.energy_per_session_kwh:g} kWh sessions"
        )

    sessions_per_month = i.sessions_per_day * DAYS_PER_MONTH
    energy_per_month_kwh = sessions_per_month * i.energy_per_session_kwh
    revenue_monthly = round(energy_per_month_kwh * i.tariff_idr_per_kwh
                            + sessions_per_month * i.admin_fee_idr)

    energy_cost_monthly = round(energy_per_month_kwh * i.energy_cost_idr_per_kwh)

    capex_total = i.connectors * i.capex_per_connector_idr
    margin = revenue_monthly - energy_cost_monthly - i.opex_monthly_idr

    # Zero margin is division by zero, not an infinitely good investment, so it
    # belongs on the same side of this branch as a loss.
    payback_months = capex_total / margin if margin > 0 else None

    return {
        "sessions_per_day": i.sessions_per_day,
        "sessions_per_month": sessions_per_month,
        "energy_per_month_kwh": energy_per_month_kwh,
        "capacity_sessions_per_day": capacity,
        "utilisation": i.sessions_per_day / capacity,
        "revenue_monthly_idr": revenue_monthly,
        "energy_cost_idr_per_kwh": i.energy_cost_idr_per_kwh,
        "energy_cost_monthly_idr": energy_cost_monthly,
        "opex_monthly_idr": i.opex_monthly_idr,
        "gross_margin_monthly_idr": margin,
        "capex_total_idr": capex_total,
        "payback_months": payback_months,
        "payback_years": payback_months / 12 if payback_months is not None else None,
        "net_at_horizon_idr": round(margin * 12 * i.horizon_years - capex_total),
        "breaks_even": margin > 0,
        "horizon_years": i.horizon_years,
        "assumptions": asdict(i),
    }

def sessions_from_utilisation(utilisation: float, connectors: int, power_kw: float,
                              energy_per_session_kwh: float) -> float:
    """Turn a utilisation target into the daily sessions it implies.

    A planner usually thinks in "I expect the bays to be busy a fifth of the
    time" rather than in sessions per day, and utilisation is also the figure
    that can later be compared against what nearby stations actually do.
    """
    if not math.isfinite(utilisation):
        raise ValueError(f"utilisation must be finite, got {utilisation}")
    if not 0.0 <= utilisation <= 1.0:
        raise ValueError(f"utilisation must be between 0 and 1, got {utilisation}")
    return utilisation * capacity_sessions_per_day(connectors, power_kw, energy_per_session_kwh)
